MRKT_BASE = "https://api.tgmrkt.io/api/v1"

ACTIVITIES = f"{MRKT_BASE}/activities"
ORDER_TOP = f"{MRKT_BASE}/orders/top"
ORDERS = f"{MRKT_BASE}/orders"
ORDER_CREATE = f"{MRKT_BASE}/orders/create"
ORDER_CANCEL = f"{MRKT_BASE}/orders/cancel/"
OFFER_DECLINE = f"{MRKT_BASE}/offers/decline"
OFFER_CANCEL = f"{MRKT_BASE}/offers/cancel"
OFFER_CREATE = f"{MRKT_BASE}/offers/create"
FEED = f"{MRKT_BASE}/feed"
BUY_GIFT = f"{MRKT_BASE}/gifts/buy"
CONTAINER = f"{MRKT_BASE}/gifts"
COLLECTIONS = f"{MRKT_BASE}/gifts/collections"
SALING_GIFTS = f"{MRKT_BASE}/gifts/saling"
SALE_GIFT = f"{MRKT_BASE}/gifts/sale"
BALANCE = f"{MRKT_BASE}/balance"
HISTORY = f"{MRKT_BASE}/history"

PORTALS_BASE = "https://portal-market.com/api"
PORTALS_COLLECTIONS = f"{PORTALS_BASE}/collections?offset=0&limit=150"
PORTALS_ORDERS = f"{PORTALS_BASE}/collection-offers/"
